# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 076281df7069b9e06436d3e8895e342b1cbea024e39084605096b88e4cca94b91090a7aa9e4b4b543814394fde77bbf133eba0b16c98da97059dbf299b39d98e

test:
  secret_key_base: e16eecbfac0a4d01d0f8e8366f8a6fa28efc11f72d9d1edd68aff585c12369e254b24e14437abc2ec7adfb6c1c113fa0968a9a1a85c428425909c63a2663e2bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
